Corrected path normalization.
shotgunsoftware/tk-nuke-writenode pull request #50
Opened 2023-02-10 20:59 UTC by vazquea

Changed occurrences of `replace("/", os.path.sep)` to `replace(os.path.sep, "/")` at `python/tk_nuke_writenode/handler.py` in order to actually normalize file paths across different OS.

2023-02-10 22:29 UTC, carlos-villavicencio-adsk approved these changes
LGTM!

Mention to similar fix done at https://github.com/shotgunsoftware/tk-multi-workfiles2/pull/120

2023-02-13 22:51 UTC, julien-lang requested changes
I am worried about this code change.
We seem to do that (and https://github.com/shotgunsoftware/tk-multi-workfiles2/pull/120) just because of Nuke and it does not seem right.

Also, I wonder why we had the opposite replacement before and potentially re-introducing an old bug back.

From what I understand, Nuke's API has an issue with strings containing a backslash (Windows Path). If this issue is already known on Nuke's tracker/documentation? Is there a workaround? (Like what about doubling the backslash?).

Last question: is this related to Python 3 (str/byte) or does this exist in Py2?

2023-02-13 23:00 UTC, vazquea commented
> I am worried about this code change. We seem to do that (and [shotgunsoftware/tk-multi-workfiles2#120](https://github.com/shotgunsoftware/tk-multi-workfiles2/pull/120)) just because of Nuke and it does not seem right.
> 
> Also, I wonder why we had the opposite replacement before and potentially re-introducing an old bug back.
> 
> From what I understand, Nuke's API has an issue with strings containing a backslash (Windows Path). If this issue is already known on Nuke's tracker/documentation? Is there a workaround? (Like what about doubling the backslash?).
> 
> Last question: is this related to Python 3 (str/byte) or does this exist in Py2?

Hi @julien-lang studying both cases with @NorberMV we discovered the fix is actually correct, the issue with the [shotgunsoftware/tk-multi-workfiles2#120](https://github.com/shotgunsoftware/tk-multi-workfiles2/pull/120)) is that the `.replace` call is used in multiple lines, therefore we should fix them all it that repository as well.

A workaround is to do not use paths with numbers in the `templates.yml` file, since we already know how to fix it we may create a different ticket for the Nuke issue, and fix the other `.replace` calls for the next `tk-nuke` release.

Finally, it seems to be only happening with Python 3, since Nuke 13 migrated dropped support for Python 2.7, the version used by `SG Desktop` is indifferent.

2023-03-16 01:58 UTC, carlos-villavicencio-adsk commented
I was doing some tests using [nuke as Python module](https://learn.foundry.com/nuke/developers/140/pythondevguide/nuke_as_python_module.html).

Used function [nuke.filename()](https://learn.foundry.com/nuke/developers/140/pythondevguide/_autosummary/nuke.filename.html) to get the full path of a node, got the following output:

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/123113322/225488365-acfd8bab-a11d-41b1-b02e-96a78988577f.png">

Seems like they don't have it documented but perhaps they're using forward slash even for Windows paths since Python3 supports both `\\` and `/`. This explains why this is breaking for back slashes. This is just a theory.

The fix for `__get_current_script_path` method and `__on_script_save` makes sense to me. However, we need to make sure that the other changed lines are working as expected.

2023-03-16 15:40 UTC, carlos-villavicencio-adsk commented
I can confirm all changes in this PR are working as expected. I logged the paths before the replacements to see their value. The replace is not needed at this point but I don't it's a good idea to remove them unless we have an official Nuke documentation reference about this.

When opening workfile:
```
2023-03-16 10:30:20,704 [13856 DEBUG sgtk.env.project.tk-nuke.tk-nuke-writenode] <<<<< po5i path C:/sg/data/sg_29224_nuke_path_normalization/assets/Character/foo/DSN/work/images/scene1/v003/2048x1556/foo_scene1_output_v003.%04d.exr
2023-03-16 10:30:20,706 [13856 DEBUG sgtk.env.project.tk-nuke.tk-nuke-writenode] $$$$$ script_path C:/sg/data/sg_29224_nuke_path_normalization/assets/Character/foo/DSN/work/nuke/scene1.v003.nk
```

When saving workfile:
```
2023-03-16 10:32:43,103 [13856 DEBUG sgtk.env.project.tk-nuke.tk-nuke-writenode] @@@@@ po5i last_known_path C:/sg/data/sg_29224_nuke_path_normalization/assets/Character/foo/DSN/work/nuke/scene1.v004.nk
```

When pressing "Jump to File System" button:
```
2023-03-16 10:37:12,479 [13856 DEBUG sgtk.env.project.tk-nuke.tk-nuke-writenode] >>>>> po5i render_path C:/sg/data/sg_29224_nuke_path_normalization/assets/Character/foo/DSN/work/images/scene1/v004/2048x1556/foo_scene1_output_v004.%04d.exr
```

<img width="360" alt="image" src="https://user-images.githubusercontent.com/123113322/225670101-187b222f-e984-4042-85ba-688d0bebe64c.png">

2023-03-16 16:56 UTC, julien-lang approved these changes
LGTM!

2023-03-16 21:22 UTC, merged